# Generated by Django 4.0.4 on 2022-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dependents', models.FloatField(default=0)),
                ('ApplicantIncome', models.FloatField(default=0)),
                ('CoapplicantIncome', models.FloatField(default=0)),
                ('LoanAmount', models.FloatField(default=0)),
                ('Loan_Amount_Term', models.FloatField(default=0)),
                ('Credit_History', models.FloatField(default=0)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('Married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('Education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not_Graduated', 'Not_Graduated')], max_length=15)),
                ('Self_Employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('Property_Area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=15)),
            ],
        ),
    ]
